PrimeFaces.locales['zh'] = {
	closeText : '关闭',
	prevText : '向前',
	nextText : '向后',
	monthNames : [ '一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月',
			'十一月', '十二月' ],
	monthNamesShort : [ '一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月',
			'十月', '十一月', '十二月' ],
	dayNames : [ '周日', '周一', '周二', '周三', '周四', '周五', '周六' ],
	dayNamesShort : [ '日', '一', '二', '三', '四', '五', '六' ],
	dayNamesMin : [ '日', '一', '二', '三', '四', '五', '六' ],
	weekHeader : '星期',
	FirstDay : 1,
	isRTL : false,
	showMonthAfterYear : false,
	yearSuffix : '',
	timeOnlyTitle : '时间',
	timeText : '时间',
	hourText : '时',
	minuteText : '分',
	secondText : '秒',
	currentText : '当前时间',
	ampm : false,
	month : '月',
	week : '周',
	day : '天',
	allDayText : '全天'
};
PrimeFaces.locales['en'] = {
		closeText : 'close',
		prevText : 'Next',
		nextText : 'Prev',
		monthNames : [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
				'Nov', 'Doc' ],
		monthNamesShort : [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
		    				'Nov', 'Doc' ],
		dayNames : [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' ],
		dayNamesShort : [ 'Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa' ],
		dayNamesMin : [ 'Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa' ],
		weekHeader : '',
		FirstDay : 1,
		isRTL : false,
		showMonthAfterYear : false,
		yearSuffix : '',
		ampm : false,
		month : 'Month',
		week : 'Week',
		day : 'Day',
		allDayText : 'All Day'
	};